# Generated by Django 3.1.1 on 2020-09-25 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ftl', '0003_remove_activitytracker_user_linked'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activitytracker',
            name='end_time',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='activitytracker',
            name='start_time',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='activitytracker',
            name='tz',
            field=models.TextField(null=True),
        ),
    ]
