# Generated by Django 3.1.1 on 2020-09-25 16:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ftl', '0006_activity'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='user_linked',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='userliked', to='auth.user'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='activity',
            name='end_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='activity',
            name='start_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='activity',
            name='tz',
            field=models.TextField(blank=True, null=True),
        ),
    ]
